export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
  GOAL_ARCHIVED: 'GOAL_ARCHIVED',
  GOAL_FORBIDDEN: 'GOAL_FORBIDDEN',
  PDCA_NOT_FOUND: 'PDCA_NOT_FOUND',
  PDCA_INVALID_STATUS: 'PDCA_INVALID_STATUS',
  PDCA_ALREADY_COMPLETED: 'PDCA_ALREADY_COMPLETED',
  PDCA_FORBIDDEN: 'PDCA_FORBIDDEN',
  GACHA_NO_DRAW_AVAILABLE: 'GACHA_NO_DRAW_AVAILABLE',
  GACHA_NO_ACTIVE_CHARACTER: 'GACHA_NO_ACTIVE_CHARACTER',
  GACHA_NOT_CONFIGURED: 'GACHA_NOT_CONFIGURED',
  RECOVERY_NOT_AVAILABLE: 'RECOVERY_NOT_AVAILABLE',
  CHARACTER_NOT_OWNED: 'CHARACTER_NOT_OWNED',
  GUEST_INVALID_DATA: 'GUEST_INVALID_DATA',
  GUEST_ALREADY_MIGRATED: 'GUEST_ALREADY_MIGRATED',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
